Squashed 'evfibers/' changes from d17d37d..1ff4825
1ff4825 Merge pull request #5 from miihael/master
9fa5cd4 fix 'undefined reference to symbol floor@@GLIBC' when linking tests

git-subtree-dir: evfibers
git-subtree-split: 1ff48255d4f48b21ae5727000617fc3bab6d953f